// Stage 2: Cloudflare AI Llama 3.1 8B to generate comprehensive CLI documentation
// Generates installation, command reference, examples, and configuration sections

import { GitHubRepo } from '../types';

export async function generateCliDocs(
  repo: GitHubRepo,
  readme: string,
  ai?: any
): Promise<string> {
  console.log(`[Stage 2] Generating CLI docs for ${repo.owner}/${repo.repo} using Llama 3.1 8B...`);

  // Fallback if AI is not available
  if (!ai) {
    console.log('[Stage 2] AI not available, returning basic markdown');
    return generateBasicMarkdown(repo, readme);
  }

  // Truncate README if needed
  const truncatedReadme = readme.length > 8000
    ? readme.substring(0, 8000) + '\n\n[README truncated...]'
    : readme;

  const prompt = `You are a technical documentation expert. Analyze this GitHub repository README and generate comprehensive CLI documentation.

Extract and format the following sections:

1. **Installation** - All installation methods (npm, yarn, cargo, pip, etc.)
2. **Command Reference** - Complete list of commands with descriptions and options
3. **Examples** - Practical usage examples
4. **Configuration** - Configuration files, environment variables, and options

Format the output as clean markdown with:
- Clear headings and subheadings
- Code blocks for commands
- Tables for options/flags when applicable
- Bullet points for lists

Repository: ${repo.owner}/${repo.repo}

README:
\`\`\`
${truncatedReadme}
\`\`\`

Generate the complete CLI documentation in markdown format:`;

  try {
    // Call Cloudflare AI with Llama 3.1 8B fast model
    const response = await ai.run('@cf/meta/llama-3.1-8b-instruct-fast', {
      prompt: prompt,
      max_tokens: 2048,
      temperature: 0.3
    });

    const generatedContent = response?.response || '';
    console.log(`[Stage 2] Generated ${generatedContent.length} characters`);

    // Wrap with header and footer
    const fullMarkdown = `# ${repo.repo}

Source: github.com/${repo.owner}/${repo.repo}

${generatedContent}

---

*Generated by clidocs.io*
*AI Model: Llama 3.1 8B via Cloudflare Workers AI*`;

    return fullMarkdown;

  } catch (error) {
    console.error('[Stage 2] AI error:', error);
    console.log('[Stage 2] Falling back to basic markdown');
    return generateBasicMarkdown(repo, readme);
  }
}

function generateBasicMarkdown(repo: GitHubRepo, readme: string): string {
  // Extract title from first line
  const lines = readme.split('\n');
  const title = lines[0]?.replace(/^#+\s*/, '') || repo.repo;

  // Try to find installation section
  let installSection = '';
  const installIndex = lines.findIndex(line =>
    line.toLowerCase().includes('install') && line.startsWith('#')
  );
  if (installIndex >= 0) {
    // Capture until next heading or end
    let endIndex = lines.slice(installIndex + 1).findIndex(line => line.startsWith('#') && !line.startsWith('##'));
    if (endIndex === -1) endIndex = Math.min(installIndex + 20, lines.length);
    installSection = lines.slice(installIndex, installIndex + endIndex + 1).join('\n');
  }

  return `# ${title}

Source: github.com/${repo.owner}/${repo.repo}

${installSection || '## Installation\n\n\`\`\`bash\nnpm install -g ' + repo.repo + '\n\`\`\`'}

## Overview

Please visit the repository for full documentation.

---

*Generated by clidocs.io*
*Note: AI generation failed, showing basic extraction only.*`;
}
