// Stage 2: Better LLM to generate CLI documentation
// Currently returns mock data

import { GitHubRepo } from '../types';

export async function generateCliDocs(
  repo: GitHubRepo,
  readme: string,
  ai?: any
): Promise<string> {
  // MOCK IMPLEMENTATION
  // In production, this would call Claude Haiku or GPT-4o-mini
  
  console.log(`[Stage 2] Generating CLI docs for ${repo.owner}/${repo.repo}...`);
  
  // Extract basic info from README (mock parsing)
  const lines = readme.split('\n');
  const title = lines[0]?.replace(/^#+\s*/, '') || repo.repo;
  
  // Find installation section
  let installSection = '';
  const installIndex = lines.findIndex(line => 
    line.toLowerCase().includes('install')
  );
  if (installIndex >= 0) {
    installSection = lines.slice(installIndex, installIndex + 5).join('\n');
  }

  // Generate mock markdown
  const mockMarkdown = `# ${title}

Source: github.com/${repo.owner}/${repo.repo}

## Overview

This is a CLI tool. Full documentation would be extracted here using a premium LLM (Claude Haiku or GPT-4o-mini).

## Installation

${installSection || '```bash\nnpm install -g ' + repo.repo + '\n```'}

## Usage

CLI documentation would be intelligently parsed and structured here.

### Commands

- \`command1\` - Description of command 1
- \`command2\` - Description of command 2
- \`command3\` - Description of command 3

### Options

| Flag | Description |
|------|-------------|
| \`-h, --help\` | Show help |
| \`-v, --version\` | Show version |
| \`-d, --debug\` | Enable debug mode |

## Examples

\`\`\`bash
# Example usage
${repo.repo} --help
${repo.repo} command1 --option value
\`\`\`

---

*Generated by clidocs.io*  
*Note: This is mock data. Connect a premium LLM for real documentation.*
`;

  return mockMarkdown;
}
