name = "clidocs"
main = "src/index.ts"
compatibility_date = "2024-02-22"

[[kv_namespaces]]
binding = "CLIDOCS_CACHE"
id = "dd332d8dc6b44c21bf0e715a6b68c294"

[vars]
# Add your GitHub token here or use wrangler secret
# GITHUB_TOKEN = ""

[[ai]]
binding = "AI"
